version: "3.8"

services: 
  control_finance_db_development:
    image: bitnami/postgresql:latest
    ports: 
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=controlFinanceRoot
      - POSTGRESQL_PASSWORD=controlFinance
      - POSTGRESQL_DATABASE=controlFinance
    volumes:
      - control_finance_db_data_development:/bitnami/postgresql

volumes:
  control_finance_db_data_development:
